### ISSUE TITLE
Alternative UI

### ISSUE THREAD

**Issue by JonaBrackenwood** [Darkside138/DiscordSoundboard#133]
I've had some fun and made an alternative UI with Bootstrap.
It includes scalable category navigation, buttons for random, stop and settings which opens a settings-menu to search sounds, select the user, select the volume and toggle some colors.

I haven't got anything setup to make pull requests, so I've put in a gist. Only index.html needed.
https://gist.github.com/JonaBrackenwood/3bd0af3badb7ddc0f9269a8a35fca850

Feel free to use if you want to.

![BootstrapSoundboard](https://user-images.githubusercontent.com/1567798/77851537-12c60d00-71da-11ea-9e10-f4118dd75c7f.png)

**Comment by Darkside138** [comment]
This is awesome! I've been hoping someone would magically come along and
make a new UI that was better than what I threw together!

I've put this on my personal soundboard to test it out. I even added an
update myself. I made it so that you can add a URL param to override the
default user selected so that users can bookmark a personalized link that
pre-selects them instead of the default in the configuration.

Thank you so much for your contribution. After a bit of testing, I'll add
this to the release so everyone can enjoy it.

Dave

**Comment by jooonah** [comment]
Thanks, Jona, this UI is really cool! 

On the other hand, I would have something to ask you about. Would it be possible for us to talk on discord? This is really important to me and I'd appreciate it a ton if you could add me (Jooonah#6329). 

Thanks for taking the time to read this!
- Jooonah

**Comment by Darkside138** [comment]
Implemented in the latest version. Love it. Thanks for your contribution!!
