### ISSUE TITLE
Avatar wont change.

### ISSUE THREAD

**Issue by JoshCarlyle** [Darkside138/DiscordSoundboard#47]
I've replaced avatar.jpg with an image that I want (renaming it to avatar.jpg ofcourse) however it still uses the duke nukem avatar. Any help?

**Comment by samuscherer** [comment]
Have you tried to change it via the Discord developers page?

**Comment by z1g** [comment]
I used this URL to change the avatar for my bot:

https://blastsoftstudios.com/dac.html

**Comment by samuscherer** [comment]
I recommend using the developers page:
https://discordapp.com/developers/applications/me

**Comment by z1g** [comment]
The developers page will not change the avatar in app it will only change it as it appears on the applications page. If you want to change the bots in app avatar it needs be done via the API such as provided by the link I supplied above.

**Comment by samuscherer** [comment]
If I change the avatar via the developers page, Discord instantly shows the new image. But maybe we're talking about different things?

**Comment by z1g** [comment]
I believe if you set the app icon before clicking "Create Bot User" when creating the bot application you will be able to change the avatar by changing the app icon. However if you set the app icon afterwards it will have no effect.

That has been my experience in any event, as well has multiple others which is why the site I posted was created by a reddit user. Seems to happen for many bots, not just this one.

**Comment by samuscherer** [comment]
Ok. That's interesting. I'll keep an eye on that when I create a new bot.
