### ISSUE TITLE
'Unknown File Format' with some MP3 Files

### ISSUE THREAD

**Issue by InjuredWolf** [Darkside138/DiscordSoundboard#70]
One of the files I have refuses to play in the bot

Error: https://pastebin.com/80DX1PCT

The file in question is this: [fiveminutes.zip](https://github.com/Darkside138/DiscordSoundboard/files/1167836/fiveminutes.zip)

Audacity shows this as a mono 48KHz file, 32-bit float: 
![image](https://user-images.githubusercontent.com/10350531/28496259-64e3afc8-6faa-11e7-9fcc-7246e15414ae.png)

EDIT: Pastebin link due to GitHub not having spoiler tags

**Comment by Penetrosity** [comment]
I've run into this same problem, I was using the master branch andw as having issues with mono mp3 files so I switched over to the JDA3 branch, I've honestly no idea if there's a difference because either way I was grabbing version 2.0.1

This [file](
[VGTL.zip](https://github.com/Darkside138/DiscordSoundboard/files/1182112/VGTL.zip)
) is giving me this [error](https://pastebin.com/7PBf9FMq)

**Comment by Darkside138** [comment]
Yes, the master branch version has issues with mono files and does not play them back correctly. The JDA3 branch should handle them better.
